---
# name: nmos-registration-setup/defaults
# description: The default variables for nmos-registration

packages: # Packages required
  - python3
  - python3-pip
  - libsystemd-dev
  - build-essential
  - python3-dev
  - python3-apt
  - python-apt
  - python-pip
  - tox
  - xz-utils
  - virtualenv

docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

couchbase_sdk_packages: # Couchbase SDK packages required (separate to install after installing .deb)
  - libcouchbase-dev
  - libcouchbase2-bin

reg_config_install_path: /etc/ips-regaggregator

reg_config_owner: vagrant

reg_working_dir: /vagrant

discovery_config:
  registry:
    type: couchbase
    hosts: 127.0.0.1
    port: 8091
    username: vagrant
    password: ""
    buckets:
      registry: registry
      meta: meta
